
enc:
  utm_zone: 32
  size: [1800.0, 1006.20]                                                  # width, height (east, north) window to consider map data from. Unit is distance in meters
  origin: [569747.80, 7035179.12]                                            # easting/northing origin (UTM zone 33N) as an example
  # origin: [570102.58, 7035529.73]                                            # easting/northing origin (UTM zone 33N) as an example
  # origin: [569703.81, 7035269.56]                                            # easting/northing origin (UTM zone 33N) as an example
  buffer: 0                                                               # int of dilation or erosion distance for geometries
  tolerance: 0                                                            # int of maximum tolerance distance for geometries
  layers: ["seabed", "land", "shore"]                                     # list(str...) of feature layers to load or show
  depths: [0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500]                       # list(int...) of depth bins for feature layers
  files: ["Basisdata_50_Trondelag_25832_Dybdedata_FGDB.gdb"]                                          # seacharts source database name
  new_data: True                                                          # bool indicating if new files should be parsed
  raw_data: False
  border: False                                                           # bool for showing a border around the environment plot
  verbose: True                                                           # bool for status printing during geometry processing
  #origin_lla: [62.457464, 6.146678]                                       # origin in latitude longitude (degrees) for transformation purposes (NOT IMPLEMENTED YET)
  sim_callback_time: 5
  local_traffic_publish_timer: 0.01

display:
  dpi: 96
  anchor: "center"
  resolution: 1080
  fullscreen_mode: False
  colorbar_mode: True
  dark_mode: False
  draw_names: False # Buggy
  nr_of_shadow_ships: 10

ais:
  timer_period: 10